### ISSUE TITLE
Error when unmounting Editor.js

### ISSUE THREAD

**Issue by brandontle** [stfy/react-editor.js#1]
Thanks for putting together a React wrapper!

I'm hitting a little issue here that [others also seem to be running into](https://github.com/codex-team/editor.js/issues/733). 

When leaving a page with EditorJS loaded (via the wrapper), the screen loads a blank white page and the console prints a bunch of errors:

```
Uncaught TypeError: this.editor.destroy is not a function
//...
Module UI was skipped because of Error: Holder wasn't found by ID: #editorjs
//...
Module DragNDrop was skipped because of TypeError: Cannot read property 'addEventListener' of null
//...
Module RectangleSelection was skipped because of TypeError: Cannot read property 'querySelector' of null
//..
Uncaught TypeError: Cannot read property 'children' of null
//...
Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
```

Somehow, I think EditorJs is being unmounted twice (checked via console.logs). The first time, destroy() exists and is called correctly; however, the second time, destroy() does not exist (and EditorJs is not ready), so it throws an error. 

As a temporary solution, adding a conditional to the react-wrapper's componentWillUnmount like so:
```
componentWillUnmount() {
    if (typeof this.editor.destroy !== 'undefined') {
      this.editor.destroy();
    }
  }
```
fixes the `this.editor.destroy is not a function` error. I still am receiving the other errors and haven't got to the root cause yet. If anyone has ideas, do chime in!

**Comment by stfy** [comment]
@brandontle , thanks for issue. It's really happens because `this.editor.destroy()` executing twice. But i can't found use case where it befall. Can you provide more information about case of problem ? 

Thanks.

**Comment by brandontle** [comment]
That solved it; thanks for the fix!

**Comment by dimuska139** [comment]
@stfy I have a similar problem

![Peek 2019-06-05 17-03](https://user-images.githubusercontent.com/10630525/58962618-47348c80-87b4-11e9-88f9-43e95f8b9687.gif)

**Comment by dimuska139** [comment]
@stfy I suppose that this fix should solve problem:

```js
_destroyEditor = () => {
    if (!this.editor || !(this.editor.destroy instanceof Function)) return;

    this.editor.destroy();
    this.editor = null;
};
```

**Comment by Biaggio74** [comment]
@brandontle  what is the fix exactly here, and where to update the _destroyEditor function?

**Comment by stfy** [comment]
@Biaggio74, what's the version of the package do you use ?

This solved in https://github.com/stfy/react-editor.js/commit/30eabaaeaf04c574e238767e6d24e6ba2f398bfb

**Comment by brandontle** [comment]
@Biaggio74 I no longer use Editor.js, but in addition to the above, I believe adding this check in `componentWillUnmount` did the trick for me: 

```
componentWillUnmount() {
    if (typeof this.editor.destroy !== 'undefined') {
      this._destroyEditor();
    }
  }
```

Feel free to check out my fork if needed: 
https://github.com/brandontle/react-editor.js/blob/master/src/editor.js

**Comment by Biaggio74** [comment]
@brandontle thanks for the tip :) ...in the meantime I also moved back to my "old" Trix editor. (for sake of integration issues and a short project timeframe)

**Comment by Biaggio74** [comment]
@stfy my npm version currently is 6.9.0, ...but I cannot be sure this was the one at the time of commenting the issue. I made an update recently.
