### ISSUE TITLE
How to use it with image tool

### ISSUE THREAD

**Issue by wilfredonoyola** [stfy/react-editor.js#11]
Hi guys,

I am trying to integrate with image and https://github.com/editor-js/image

But I am not sure how to do it.

Let me know your thoughts.

Thanks,

**Comment by stfy** [comment]
@wilfredonoyola,  install @editorjs/image, import it and pass in editor.js as prop

`
import Image from '@editorjs/image'; 

<Editor
      tools={{
         image: Image
      }}
>
`

**Comment by wilfredonoyola** [comment]
Thanks!!!

**Comment by gabrielmoterani** [comment]
What i'm doing wrong?
`<EditorJS
          autofocus
          data={text}
          onChange={(event) => {onTextChange(event)}}
          tools={{
            header: {
              class: Header,
              inlineToolbar: true,
              shortcut: 'CMD+SHIFT+H'
            },
            image: {
              Image,
              config: {
                endpoints: {
                  byFile: `${API_URL}/utils/image`, // Your backend file uploader endpoint
                  byUrl: `${API_URL}/utils/url_image`, // Your endpoint that provides uploading by Url
                }
              }
           }
        }
/>
`

Image Appears on editorjs but the request is made to browser url


`
Request URL: http://localhost:3000/editor/26
Request Method: POST
Status Code: 404 Not Found
Remote Address: 127.0.0.1:3000
Referrer Policy: no-referrer-when-downgrade
`
