### ISSUE TITLE
Support for UUID's wanted

### ISSUE THREAD

**Issue by bosgeluk** [stfy/react-editor.js#14]
To track changes inside the editor and to attach other data to each block an UUID would be very welcome. As discussed in: https://github.com/codex-team/editor.js/issues/873

**Comment by mqtik** [comment]
Did you managed to solve this?
Care to share?

**Comment by bosgeluk** [comment]
Not to my satisfaction. Beside that I switched to a different editor very shortly after other issues I encountered, like reloading without finishing a previous load. That issue I wasn't able to solve and that was a showstopper for me.
