### ISSUE TITLE
Holder ID error

### ISSUE THREAD

**Issue by PatrickBokhove** [stfy/react-editor.js#16]
When i use the exact example from the readme, it will instantly throw an error, saying it can't assign holder and holderId at the same time.

![image](https://user-images.githubusercontent.com/7600895/70622858-1c246d00-1c1d-11ea-8e75-e53f3f19ac1c.png)

When i remove the holderId prop, the editor will render, but onChange and onReady won't return any data.

**Comment by stfy** [comment]
@PatrickBokhove , holderId is deprecated in editor.js, you should use holder property to mount editro.js instance. 

In release 1.0.3 i am refactor onChange, that callback no longer returns data and only notify about changes in editor.js instance (see onChange). OnReady was removed and to access data you should use onData prop, that prop sanitize data before emit it;
