### ISSUE TITLE
Show only default Editor

### ISSUE THREAD

**Issue by sabit990928** [stfy/react-editor.js#17]
I started implementing your react-editor to my project and it shows default view. I can enter some text, but when I trying to add some excludeDefaultTools it ignore everything. It also ignore holderId 
`index.js:1 Editor.js is not ready because of Error: «holderId» and «holder» param can't assign at the same time.`

Is this editor work properly in your project?

**Comment by sabit990928** [comment]
Как я понял, разработчики из русские.
Перед загрузкой вашей библиотеки я скачивал непосредственно сам editorjs.
Показывается изначальный вид с простым текстом. Данные введенные тоже не возвращаются. Как сказал раньше и не возвращаются тулзы которые добавлял. 

Что делать? Использовал ваш пример тоже. Но там даже изначально заданные данные ломаются
![Снимок экрана от 2019-12-24 14-31-58](https://user-images.githubusercontent.com/37778327/71405499-d1184a00-265f-11ea-9998-28f5287ae0d1.png)

**Comment by stfy** [comment]
@sabit990928, попробуйте добавить плагин @editorjs/header при инициализации в tools:

`<EditorJS tools={{header: Header}}>`

**Comment by sabit990928** [comment]
@stfy, Cпасибо за ответ. Ввел как и сказали. Все равно не работает и выводит undefined при выводе данных. 
И такой вопрос, я видел ещё одну библиотеку там где вы и ещё один человек. Есть ли в них разница?
И знаете ли вы как работают другие альтернативные библиотеки. Я нашел react-editor-js, там с тулзами норм, но не могу сохранить данные. 
Не легче ли будет написать свою обертку для этого едитора, если да, то можете дать пару советов по реализаций
```
import React from 'react'
import Header from '@editorjs/header'
import Embed from '@editorjs/embed'
import List from '@editorjs/list'
import { Button } from 'antd'
import EditorJS from '@stfy/react-editor.js'

 render() {
    return (
      <>
        <EditorJS
          excludeDefaultTools={{ header: Header }}
          onChange={data => console.log('entered data: ', data)}
        />
```

**Comment by sabit990928** [comment]
Если я использую tools параметр вместо excludeDefaultTools, то все норм показывает и пишет. Но опять таки не могу понять как и где вызвать save()

**Comment by sabit990928** [comment]
Получилось реализовать с помощью этой https://github.com/Jungwoo-An/react-editor-js библиотеки. Там я в issue прописал как надо стягивать данные
