### ISSUE TITLE
How can I use render to reload new content?

### ISSUE THREAD

**Issue by Jeel-Shah** [stfy/react-editor.js#19]
Hello,

editor.js provides a render method to load new data into the editor instance. Is there a way to render new data through the component? Do we have access to the editor instance?

Thanks a bunch

**Comment by stfy** [comment]
@Jeel-Shah, it can handle by data prop and reinitOnPropsChange=true. To access editor instance add ref to component `<EditorJS ref={ref => {this.editorApi = ref.editor}} {...anotherProps}>`, 
and use it by `await this.editor.isReady` for example

**Comment by Jeel-Shah** [comment]
Wonderful! Setting `reinitOnPropsChange=true` and then updating the data works perfectly. Thank you!
