### ISSUE TITLE
Editor.js is not ready because of TypeError: Cannot create property 'blocks' on string

### ISSUE THREAD

**Issue by SohaibShafiq1** [stfy/react-editor.js#28]
@stfy @Jeel-Shah 
Whenever i load data from server. I got this error:
Editor.js is not ready because of TypeError: Cannot create property 'blocks' on string '{"time":1609871884879,"blocks":[{"type":"paragraph","data":{"text":"knkcncklancaklsncalkc"}},{"type":"paragraph","data":{"text":"knlkelwkelkenflk"}}],"version":"2.13.0"}'
Uncaught (in promise) TypeError: Cannot create property 'blocks' on string '{"time":1609871884879,"blocks":[{"type":"paragraph","data":{"text":"knkcncklancaklsncalkc"}},{"type":"paragraph","data":{"text":"knlkelwkelkenflk"}}],"version":"2.13.0"}'
I also perform many Parsers, html decoder to convert it into html but attempts sucks.
Can you help me.
![Annotation 2021-01-06 170754](https://user-images.githubusercontent.com/57568754/103767088-d44f5f80-5041-11eb-9106-f15b81fbe2a0.jpg)

**Comment by SohaibShafiq1** [comment]
This is my server response
![Annotation 2021-01-06 182229](https://user-images.githubusercontent.com/57568754/103773376-ca7f2980-504c-11eb-9581-6c4c6d0bb61b.jpg)

**Comment by Jeel-Shah** [comment]
I think the error is arising from the fact that you are trying to create blocks from your description which is a string. Instead, it has to be a Javascript object. Unfortunately, I used the package with Clojurescript so I won't be able to provide exact code but you can try something like `JSON.parse`.

**Comment by SohaibShafiq1** [comment]
@Jeel-Shah  Thank you so much. Where was my brain, i was attempting to parse and markup the data but forget to use JSON.parse.
Sorry for my english.
🤘🤘🤘🤘🤘🤘🤘
