### ISSUE TITLE
Cant see the header tool

### ISSUE THREAD

**Issue by dukesx** [stfy/react-editor.js#3]
Hi , this may be a bug that when Codex editor is initialized, i see all the tools but not the HEADER tool , i tried using customTools: {{ header: Header }} , but even this did not include the header plugin. Any help would be appreciated , and thank you so so much for this awesome work ! i really appreciate, i got tired of using the default one , it was frustrating.

Edit#1: There is also an issue with a placeholder being shown again and again for no reason " Tell your story " 
Picture : 
![issue](https://user-images.githubusercontent.com/5988991/57385564-17ea2a00-71cc-11e9-99fb-678e45c0713a.png)

**Comment by Biaggio74** [comment]
@dukesx Have you used the code snippet from the example? It might be because the Header tool was excluded by the excludeDefaultTools props. BTW, have you managed to render the editor properly? I am getting an error: _this.editor.destroy is not a function
Could you share your implementation?
